# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://mingyueli.com/cn

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             /cn

title:               Mingyue Li 

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Hello friend! Welcome to my blog’s homepage! You can return to my [Home](http://mingyueli.com).

  
  Here I can share joy and knowledge with you, but please pay attention to copyright!

# The tags listed as entries in the sidebar
sidebar_tags:        [IT, Life]

# Fallback image and color if not overwritten for tag or post
image:               /cn/public/img/nap.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Mingyue Li'

  # This photo will be used in the about section
  photo:             http://mingyueli.com/cn/public/img/flo.jpg
  photo2x:           http://mingyueli.com/cn/public/img/flo@2x.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    Hello, I am [Mingyue Li](http://mingyueli.com/).  Read my thoughts on [IT](http://mingyueli.com/cn/tag/IT) and [Life](http://mingyueli.com/cn/tag/Life)
    
    Copyright Declaration：

    All articles and pictures contained on this web site is copyright protected. 
    If reproduced, must contain this statement, and indicate the original author and the original address of this article
  # 介绍
  introduce:

  # 关于我
  me:

  # 声明
  statement:

  # 联系方式
  contact:

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # facebook:        _username_
    # twitter:         _username_
    google:          UA-93963635-1
    github:          lmy1223
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# Disqus
disqus:            mingyueli-com

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

